<?php

/**
 * Retrieves a CiviCRM contact by Drupal user ID.
 */
function civicrm_custom_user_profile_get_contact($uid) {
  $contacts = &drupal_static(__FUNCTION__);
  if (isset($contacts[$uid])) {
    return $contacts[$uid];
  }
  if (!isset($contacts)) {
    $contacts = array();
  }
  $contacts[$uid] = FALSE;
  civicrm_initialize();
  require_once 'api/api.php';
  $res = civicrm_api('uf_match', 'get', array('uf_id' => $uid, 'version' => 3));
  if ($res['is_error'] || empty($res['id']) || empty($res['values'][$res['id']])) {
    return FALSE;
  }
  $id = $res['values'][$res['id']]['contact_id'];
  $res = civicrm_api('contact', 'get', array('contact_id' => $id, 'version' => 3));
  if ($res['is_error']) {
    return FALSE;
  }
  $contacts[$uid] = $res['values'][$res['id']];
  return $contacts[$uid];
}

/**
 * Implements hook_user_view().
 * We'll modify the title on the user profile 
 * and add a global $civi_user variable that we can 
 * expose in the profile page template
 */
function civicrm_custom_user_profile_user_view($account, $view_mode, $langcode) {
  
  global $civi_user;
  $user = user_load(arg(1));
  $uid = $user->uid;
  $civi_user = civicrm_custom_user_profile_get_contact($uid);

  if ($civi_user['display_name']) {
    drupal_set_title($civi_user['display_name']);
  } 
  
}

